/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nirmata/kube-static-egress-ip/pkg/apis/egressip/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStaticEgressIPs implements StaticEgressIPInterface
type FakeStaticEgressIPs struct {
	Fake *FakeSamplecontrollerV1alpha1
	ns   string
}

var staticegressipsResource = schema.GroupVersionResource{Group: "samplecontroller.k8s.io", Version: "v1alpha1", Resource: "staticegressips"}

var staticegressipsKind = schema.GroupVersionKind{Group: "samplecontroller.k8s.io", Version: "v1alpha1", Kind: "StaticEgressIP"}

// Get takes name of the staticEgressIP, and returns the corresponding staticEgressIP object, and an error if there is any.
func (c *FakeStaticEgressIPs) Get(name string, options v1.GetOptions) (result *v1alpha1.StaticEgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(staticegressipsResource, c.ns, name), &v1alpha1.StaticEgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticEgressIP), err
}

// List takes label and field selectors, and returns the list of StaticEgressIPs that match those selectors.
func (c *FakeStaticEgressIPs) List(opts v1.ListOptions) (result *v1alpha1.StaticEgressIPList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(staticegressipsResource, staticegressipsKind, c.ns, opts), &v1alpha1.StaticEgressIPList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StaticEgressIPList{ListMeta: obj.(*v1alpha1.StaticEgressIPList).ListMeta}
	for _, item := range obj.(*v1alpha1.StaticEgressIPList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested staticEgressIPs.
func (c *FakeStaticEgressIPs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(staticegressipsResource, c.ns, opts))

}

// Create takes the representation of a staticEgressIP and creates it.  Returns the server's representation of the staticEgressIP, and an error, if there is any.
func (c *FakeStaticEgressIPs) Create(staticEgressIP *v1alpha1.StaticEgressIP) (result *v1alpha1.StaticEgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(staticegressipsResource, c.ns, staticEgressIP), &v1alpha1.StaticEgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticEgressIP), err
}

// Update takes the representation of a staticEgressIP and updates it. Returns the server's representation of the staticEgressIP, and an error, if there is any.
func (c *FakeStaticEgressIPs) Update(staticEgressIP *v1alpha1.StaticEgressIP) (result *v1alpha1.StaticEgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(staticegressipsResource, c.ns, staticEgressIP), &v1alpha1.StaticEgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticEgressIP), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStaticEgressIPs) UpdateStatus(staticEgressIP *v1alpha1.StaticEgressIP) (*v1alpha1.StaticEgressIP, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(staticegressipsResource, "status", c.ns, staticEgressIP), &v1alpha1.StaticEgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticEgressIP), err
}

// Delete takes name of the staticEgressIP and deletes it. Returns an error if one occurs.
func (c *FakeStaticEgressIPs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(staticegressipsResource, c.ns, name), &v1alpha1.StaticEgressIP{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStaticEgressIPs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(staticegressipsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.StaticEgressIPList{})
	return err
}

// Patch applies the patch and returns the patched staticEgressIP.
func (c *FakeStaticEgressIPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StaticEgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(staticegressipsResource, c.ns, name, pt, data, subresources...), &v1alpha1.StaticEgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticEgressIP), err
}
