apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticegressips.staticegressips.nirmata.io
spec:
  group: staticegressips.nirmata.io
  names:
    kind: StaticEgressIP
    plural: staticegressips
    singular: staticegressip
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      egressip:
                        type: string
                      service-name:
                        type: string
                      cidr:
                        type: string
            status:
              type: object
              properties:
                gateway-node:
                  type: string
                gateway-ip:
                  type: string
