apiVersion: v1
kind: ConfigMap
metadata:
  name: static-egress-ip-configmap
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-egressip-gateway-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: static-egressip-gateway-manager
  replicas: 3
  template:
    metadata:
      labels:
        name: static-egressip-gateway-manager
    spec:
      serviceAccount: static-egressip-controller
      serviceAccountName: static-egressip-controller
      containers:
      - name: static-egressip-gateway-manager
        image: nirmata/static-egressip-gateway-manager:latest
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
