apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-egressip-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: static-egressip-controller
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
      - configmaps
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
    - "staticegressips.nirmata.io"
    resources:
      - staticegressips
    verbs:
      - list
      - get
      - watch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: static-egressip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: static-egressip-controller
subjects:
- kind: ServiceAccount
  name: static-egressip-controller
  namespace: kube-system
