/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	egressipv1alpha1 "github.com/nirmata/kube-static-egress-ip/pkg/apis/egressip/v1alpha1"
	versioned "github.com/nirmata/kube-static-egress-ip/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nirmata/kube-static-egress-ip/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nirmata/kube-static-egress-ip/pkg/client/listers/egressip/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StaticEgressIPInformer provides access to a shared informer and lister for
// StaticEgressIPs.
type StaticEgressIPInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StaticEgressIPLister
}

type staticEgressIPInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStaticEgressIPInformer constructs a new informer for StaticEgressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStaticEgressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStaticEgressIPInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStaticEgressIPInformer constructs a new informer for StaticEgressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStaticEgressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecontrollerV1alpha1().StaticEgressIPs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecontrollerV1alpha1().StaticEgressIPs(namespace).Watch(options)
			},
		},
		&egressipv1alpha1.StaticEgressIP{},
		resyncPeriod,
		indexers,
	)
}

func (f *staticEgressIPInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStaticEgressIPInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *staticEgressIPInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&egressipv1alpha1.StaticEgressIP{}, f.defaultInformer)
}

func (f *staticEgressIPInformer) Lister() v1alpha1.StaticEgressIPLister {
	return v1alpha1.NewStaticEgressIPLister(f.Informer().GetIndexer())
}
